#!/usr/bin/env bash

set $mod Mod4
set $alt Mod1
floating_modifier $mod

font pango:Hack 10

################################
### EXEC AT INITIAL i3 START ###
################################

# xss-lock deamon for events (lid closing)
exec --no-startup-id xss-lock --transfer-sleep-lock -- ~/.bin/screenlock lid &

# start with a random background
exec --no-startup-id sleep 2 && nitrogen --no-recurse --set-scaled --random ~/Pictures/wallpapers/ &

# Enabling Touchpad tapping
exec --no-startup-id xinput set-prop "$(xinput list | rg "Touchpad\s+id=(\d+)" -or '$1')" "libinput Tapping Enabled" 1 &

# Dunst
exec --no-startup-id dunst &

# Picom
exec --no-startup-id picom &

# mpd
exec --no-startup-id mpd &

# mpdDris2 for playerctl & mpd
exec --no-startup-id mpdDris2 &

# players discovery
exec --no-startup-id sleep 1 && playerctld daemon &

# NetworkManager applet
# exec_always --no-startup-id nm-applet &

# Start with main monitor only
# exec --no-startup-id ~/.bin/monitor main &
# Try to start with both monitors
# exec --no-startup-id ~/.bin/monitor both &

#############################################
### RE-EXEC AT EVERY i3 RESTART (ORDERED) ###
#############################################

# Always restore previous screen brightness
exec_always --no-startup-id light -I &

# Polybar
exec_always --no-startup-id ~/.config/polybar/launch.sh &

# Battery monitoring
exec_always --no-startup-id ~/.bin/battery -l 20 -h 99 -i 12 &

# Autosuspend
exec_always --no-startup-id ~/.bin/screenlock autosusp &

###################
### KEYBINDINGS ###
###################

### i3 ###

# reload i3 config
bindsym $mod+Shift+c reload
# restart i3 session (preserve layout)
bindsym $mod+Shift+r restart
# logout X session
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'Do you really want to exit i3 and logout?' -B 'Y' 'i3-msg exit'"
# save/restore i3 layout
bindsym ctrl+$alt+s exec --no-startup-id i3-resurrect save
bindsym ctrl+$alt+r exec --no-startup-id i3-resurrect restore

### MEDIA ###

# mic
bindsym XF86AudioMicMute exec --no-startup-id pamixer --default-source --toggle-mute && ~/.bin/microphone &
# speakers
bindsym XF86AudioMute exec --no-startup-id pamixer --toggle-mute && ~/.bin/volume speakers &
bindsym XF86AudioLowerVolume exec --no-startup-id pamixer -d 5 && ~/.bin/volume speakers &
bindsym XF86AudioRaiseVolume exec --no-startup-id pamixer -i 5 && ~/.bin/volume speakers &
# playerctl: spotify only (main)
bindsym XF86AudioPlay exec --no-startup-id playerctl -p spotify play-pause
bindsym XF86AudioStop exec --no-startup-id playerctl -p spotify stop
bindsym XF86AudioPrev exec --no-startup-id playerctl -p spotify previous
bindsym XF86AudioNext exec --no-startup-id playerctl -p spotify next
bindsym Shift+XF86AudioPlay exec --no-startup-id "killall -q mpd mpDris2; spotify &" 
bindsym Shift+XF86AudioStop exec --no-startup-id killall -q spotify
bindsym Shift+XF86AudioPrev exec --no-startup-id playerctl -p spotify position 5-
bindsym Shift+XF86AudioNext exec --no-startup-id playerctl -p spotify position 5+
# bindsym Shift+XF86AudioMute exec --no-startup-id playerctl -p spotify volume 0 && ~/.bin/volume spotify &
bindsym Shift+XF86AudioLowerVolume exec --no-startup-id playerctl -p spotify volume 0.05- && ~/.bin/volume spotify &
bindsym Shift+XF86AudioRaiseVolume exec --no-startup-id playerctl -p spotify volume 0.05+ && ~/.bin/volume spotify &
# playerctl: mpd only
bindsym XF86AudioPlay+$alt exec --no-startup-id playerctl -p mpd play-pause
bindsym XF86AudioStop+$alt exec --no-startup-id playerctl -p mpd stop
bindsym XF86AudioPrev+$alt exec --no-startup-id playerctl -p mpd previous
bindsym XF86AudioNext+$alt exec --no-startup-id playerctl -p mpd next
bindsym Shift+XF86AudioPlay+$alt exec --no-startup-id "killall -q spotify; mpd && mpDris2 &"
bindsym Shift+XF86AudioStop+$alt exec --no-startup-id killall -q mpd mpDris2
bindsym Shift+XF86AudioPrev+$alt exec --no-startup-id playerctl -p mpd position 5-
bindsym Shift+XF86AudioNext+$alt exec --no-startup-id playerctl -p mpd position 5+
# bindsym Shift+XF86AudioMute+$alt exec --no-startup-id playerctl -p mpd volume 0 && ~/.bin/volume mpd &
bindsym Shift+XF86AudioLowerVolume+$alt exec --no-startup-id playerctl -p mpd volume 0.05- && ~/.bin/volume mpd &
bindsym Shift+XF86AudioRaiseVolume+$alt exec --no-startup-id playerctl -p mpd volume 0.05+ && ~/.bin/volume mpd &
# playerctl: any service except spotify
# ...

### WINDOWS ###

# kill focused window
bindsym $mod+q kill
bindsym $alt+F4 kill

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# future horizontal/vertical split for active window
bindsym $alt+h split h
bindsym $alt+v split v

# fullscreen mode for active window
bindsym $mod+f fullscreen toggle

# toggle tiling / floating wm mode
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
# bindsym $mod+space focus mode_toggle

# change container layout (stacked, tabbed, toggle split)
#bindsym $mod+s layout stacking
#bindsym $mod+w layout tabbed
#bindsym $mod+e layout toggle split

### WORKSPACES ###

# set workspaces
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3

# move focused window to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3

# default workspace for specific windows
# 1
for_window [class="Firefox"] move to workspace $ws2
# 3
for_window [class="Spotify"] move to workspace $ws3

# move workspaces between monitors
bindsym $mod+n move workspace to output left
bindsym $mod+m move workspace to output right

### UTILITY ###

# set a random background
bindsym ctrl+$mod+b exec --no-startup-id nitrogen --no-recurse --set-scaled --random ~/Pictures/wallpapers/ &

# start a terminal
bindsym $mod+Return exec --no-startup-id alacritty

# start Rofi launcher
bindsym Menu exec --no-startup-id rofi -show run
bindsym $mod+Escape exec --no-startup-id ~/.bin/rofi-powermenu &

# Flameshot screenshots
bindsym ctrl+Print flameshot gui -c # manual region
bindsym Print flameshot screen -c # mouse screen

# Toggle WiFi
bindsym XF86WLAN exec --no-startup-id rfkill toggle wlan &

# Toggle touchpad
bindsym XF86TouchpadToggle exec --no-startup-id ~/.bin/touchpad &

# Select monitor
bindsym ctrl+$alt+b exec --no-startup-id ~/.bin/monitor main &
bindsym ctrl+$alt+n exec --no-startup-id ~/.bin/monitor ext &
bindsym ctrl+$alt+m exec --no-startup-id ~/.bin/monitor both &

# Brightness
bindsym XF86MonBrightnessDown exec --no-startup-id light -U 5 && light -O && ~/.bin/brightness &
bindsym XF86MonBrightnessUp exec --no-startup-id light -A 5 && light -O && ~/.bin/brightness &

# Lock
bindsym ctrl+$alt+l exec --no-startup-id ~/.bin/screenlock lock &

# Suspend
bindsym XF86Sleep exec --no-startup-id ~/.bin/screenlock susp &

#############
### MODES ###
#############

### RESIZING ###

set $mode_resize Resizing active window...
mode "$mode_resize" {
        bindsym h resize shrink width 3 px or 3 ppt
        bindsym j resize grow height 3 px or 3 ppt
        bindsym k resize shrink height 3 px or 3 ppt
        bindsym l resize grow width 3 px or 3 ppt
	bindsym Left resize shrink width 3 px or 3 ppt
        bindsym Down resize grow height 3 px or 3 ppt
        bindsym Up resize shrink height 3 px or 3 ppt
        bindsym Right resize grow width 3 px or 3 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}
bindsym $mod+r mode "$mode_resize"

### GAPS ###

# gaps top 10
gaps outer 5
gaps inner 10
default_border pixel 0
# smart_borders no_gaps
# smart_gaps on
# for_window [class="^.*"] border pixel 0
set $mode_gaps Setting gaps: Outer / Inner
set $mode_inner_gaps Inner gaps: + / - / 0 (hold Shift for global effect)
set $mode_outer_gaps Outer gaps: + / - / 0 (hold Shift for global effect)
bindsym $mod+g mode "$mode_gaps"
mode "$mode_gaps" {
        bindsym o mode "$mode_outer_gaps"
        bindsym i mode "$mode_inner_gaps"

        bindsym Escape mode "default"
        bindsym Return mode "default"
}
mode "$mode_inner_gaps" {
        bindsym plus  gaps inner current plus 2
        bindsym minus gaps inner current minus 2
        bindsym 0     gaps inner current set 0

        bindsym Shift+plus  gaps inner all plus 2
        bindsym Shift+minus gaps inner all minus 2
        bindsym Shift+0     gaps inner all set 0

        bindsym Escape mode "default"
        bindsym Return mode "default"
}
mode "$mode_outer_gaps" {
        bindsym plus  gaps outer current plus 2
        bindsym minus gaps outer current minus 2
        bindsym 0     gaps outer current set 0

        bindsym Shift+plus  gaps outer all plus 2
        bindsym Shift+minus gaps outer all minus 2
        bindsym Shift+0     gaps outer all set 0

        bindsym Escape mode "default"
        bindsym Return mode "default"
}


### PROGRAMS ###

set $mode_launcher Shortcuts: B / C / D / E / F / M / P / S / T / V / W / Z, Esc / Enter
bindsym $mod+o mode "$mode_launcher"
mode "$mode_launcher" {
    bindsym b exec bitwarden-desktop
    bindsym c exec code
    bindsym d exec discord
    bindsym e exec nemo
    bindsym f exec catfish
    bindsym m exec alacritty -e ncmpcpp
    bindsym p exec zathura
    bindsym s exec spotify
    bindsym t exec telegram-desktop
    bindsym v exec realvnc-vnc-viewer
    bindsym w exec firefox
    bindsym z exec zoom

    bindsym Escape mode "default"
    bindsym Return mode "default"
}
