#!/usr/bin/env bash

set $mod Mod4
set $alt Mod1
floating_modifier $mod

font pango:Hack 10

################################
### EXEC AT INITIAL i3 START ###
################################

# lid closing event with xss-deamon (lock & suspend)
# exec --no-startup-id xss-lock --transfer-sleep-lock -- ~/.bin/screenlock lid &

# Enabling Touchpad tapping
exec --no-startup-id xinput set-prop "$(xinput list | rg "Touchpad\s+id=(\d+)" -or '$1')" "libinput Tapping Enabled" 1 &

# Dunst
exec --no-startup-id dunst &

# Picom
exec --no-startup-id picom &

# mpd
#exec --no-startup-id mpd &

# mpdDris2 for playerctl & mpd
#exec --no-startup-id mpdDris2 &

# players discovery
exec --no-startup-id sleep 1 && playerctld daemon &

# NetworkManager applet
exec --no-startup-id nm-applet &

# start with random background and update betterlockscreen cache with the same background (but blurred)
exec --no-startup-id bkg=$(find ~/Pictures/wallpapers/ -maxdepth 1 -type f | shuf -n1) && nitrogen --no-recurse --set-scaled "$bkg" && betterlockscreen -u "$bkg" --fx blur -q &

# Start with internal monitor only
# exec --no-startup-id ~/.bin/monitor int &
# Try to start with both monitors
# exec --no-startup-id ~/.bin/monitor both &

#############################################
### RE-EXEC AT EVERY i3 RESTART (ORDERED) ###
#############################################

# Always restore previously saved screen brightness
exec_always --no-startup-id light -I &

# Polybar
exec_always --no-startup-id ~/.config/polybar/launch.sh &

# Battery monitoring
#exec_always --no-startup-id ~/.bin/battery -l 20 -h 99 -i 12 &

# Autosuspend service
#exec_always --no-startup-id ~/.bin/screenlock autosusp &

###################
### KEYBINDINGS ###
###################

### i3 ###

# reload i3 config
bindsym $mod+Shift+c reload
# restart i3 session (preserve layout)
bindsym $mod+Shift+r restart
# logout X session
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'Do you really want to exit i3 and logout?' -B 'Y' 'i3-msg exit'"
# save/restore i3 layout
bindsym ctrl+$alt+s exec --no-startup-id i3-resurrect save
bindsym ctrl+$alt+r exec --no-startup-id i3-resurrect restore

### MEDIA ###

# mic
bindsym XF86AudioMicMute exec --no-startup-id pamixer --default-source --toggle-mute && ~/.bin/microphone &
# speakers
bindsym XF86AudioMute exec --no-startup-id pamixer --toggle-mute && ~/.bin/volume speakers &
bindsym XF86AudioLowerVolume exec --no-startup-id pamixer -d 5 && ~/.bin/volume speakers &
bindsym XF86AudioRaiseVolume exec --no-startup-id pamixer -i 5 && ~/.bin/volume speakers &
# playerctl: spotify only (main)
bindsym XF86AudioPlay exec --no-startup-id playerctl -p spotify play-pause
bindsym XF86AudioStop exec --no-startup-id playerctl -p spotify stop
bindsym XF86AudioPrev exec --no-startup-id playerctl -p spotify previous
bindsym XF86AudioNext exec --no-startup-id playerctl -p spotify next
bindsym Shift+XF86AudioPlay exec --no-startup-id killall -q mpd mpDris2; spotify &
bindsym Shift+XF86AudioStop exec --no-startup-id killall -q spotify
bindsym Shift+XF86AudioPrev exec --no-startup-id playerctl -p spotify position 5-
bindsym Shift+XF86AudioNext exec --no-startup-id playerctl -p spotify position 5+
# bindsym Shift+XF86AudioMute exec --no-startup-id playerctl -p spotify volume 0 && ~/.bin/volume spotify &
bindsym Shift+XF86AudioLowerVolume exec --no-startup-id playerctl -p spotify volume 0.05- && ~/.bin/volume spotify &
bindsym Shift+XF86AudioRaiseVolume exec --no-startup-id playerctl -p spotify volume 0.05+ && ~/.bin/volume spotify &
# playerctl: mpd only
bindsym $alt+XF86AudioPlay exec --no-startup-id playerctl -p mpd play-pause
bindsym $alt+XF86AudioStop exec --no-startup-id playerctl -p mpd stop
bindsym $alt+XF86AudioPrev exec --no-startup-id playerctl -p mpd previous
bindsym $alt+XF86AudioNext exec --no-startup-id playerctl -p mpd next
bindsym $alt+Shift+XF86AudioPlay exec --no-startup-id killall -q spotify; mpd && mpDris2 &
bindsym $alt+Shift+XF86AudioStop exec --no-startup-id killall -q mpd mpDris2
bindsym $alt+Shift+XF86AudioPrev exec --no-startup-id playerctl -p mpd position 5-
bindsym $alt+Shift+XF86AudioNext exec --no-startup-id playerctl -p mpd position 5+
# bindsym $alt+Shift+XF86AudioMute exec --no-startup-id playerctl -p mpd volume 0 && ~/.bin/volume mpd &
bindsym $alt+Shift+XF86AudioLowerVolume exec --no-startup-id playerctl -p mpd volume 0.05- && ~/.bin/volume mpd &
bindsym $alt+Shift+XF86AudioRaiseVolume exec --no-startup-id playerctl -p mpd volume 0.05+ && ~/.bin/volume mpd &
# playerctl: any service except spotify
# ...

### WINDOWS ###

# kill focused container
bindsym $mod+q kill
bindsym $alt+F4 kill

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused container
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# future horizontal/vertical split for active container
bindsym $alt+h split h
bindsym $alt+v split v

# fullscreen mode for active container
bindsym $mod+f fullscreen toggle

# toggle tiling/floating wm mode
bindsym $mod+Shift+space floating toggle

# change focus between tiling/floating container
# bindsym $mod+space focus mode_toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+t layout tabbed
bindsym $mod+e layout toggle split

### WORKSPACES ###

# set workspaces name prefix
set $ws1 1
set $ws2 2
set $ws3 3

# switch to workspace
bindsym $mod+1 workspace $ws1
bindsym $mod+2 workspace $ws2
bindsym $mod+3 workspace $ws3

# move focused window to workspace
bindsym $mod+Shift+1 move container to workspace $ws1
bindsym $mod+Shift+2 move container to workspace $ws2
bindsym $mod+Shift+3 move container to workspace $ws3

# assing default workspace and switch to it
# 1. Home
for_window [class="(?i)bitwarden|firefox|obs-studio"] move container to workspace $ws1; workspace $ws1
# 2. Code
for_window [class="(?i)code|github-desktop|supernotes|virt-manager|virtualbox"] move container to workspace $ws2; workspace $ws2
# 3. Chat
for_window [class="(?i)discord|ncmpcpp|spotify|telegram|thunderbird|zoom"] move container to workspace $ws3; workspace $ws3

# move workspaces between monitors
bindsym $mod+n move workspace to output left
bindsym $mod+m move workspace to output right

### UTILITY ###

# choose a random background
bindsym ctrl+$mod+b exec --no-startup-id bkg=$(find ~/Pictures/wallpapers/ -maxdepth 1 -type f | shuf -n1) && nitrogen --no-recurse --set-scaled "$bkg" && betterlockscreen -u "$bkg" --fx blur -q &

# start a terminal
bindsym $mod+Return exec --no-startup-id alacritty

# start Rofi launcher
bindsym Menu exec --no-startup-id rofi -show run
bindsym $ctrl+Escape exec --no-startup-id ~/.bin/rofi-powermenu &

# Flameshot screenshots
# manual region
bindsym ctrl+Print exec --no-startup-id screengrab -m --region
# current screen
bindsym Print exec --no-startup-id screengrab -m --fullscreen

# Toggle WiFi
bindsym XF86WLAN exec --no-startup-id rfkill toggle wlan &

# Toggle touchpad
bindsym XF86TouchpadToggle exec --no-startup-id ~/.bin/touchpad &

# Select monitor
bindsym ctrl+$alt+b exec --no-startup-id ~/.bin/monitor int &
bindsym ctrl+$alt+n exec --no-startup-id ~/.bin/monitor ext &
bindsym ctrl+$alt+m exec --no-startup-id ~/.bin/monitor both &

# Brightness
bindsym XF86MonBrightnessDown exec --no-startup-id light -U 5 && light -O && ~/.bin/brightness &
bindsym XF86MonBrightnessUp exec --no-startup-id light -A 5 && light -O && ~/.bin/brightness &

# Lock (and turn off after 3m)
#bindsym ctrl+$alt+l exec --no-startup-id ~/.bin/screenlock lock &
bindsym ctrl+$alt+l exec --no-startup-id betterlockscreen -l blur --off 180

# Suspend (automatic lock is handled by systemd with betterlockscreen@.service, same for lid closing)
bindsym XF86Sleep exec systemctl suspend

#############
### MODES ###
#############

### RESIZING ###

set $mode_resize Resizing active container...
mode "$mode_resize" {
        bindsym h resize shrink width 3 px or 3 ppt
        bindsym j resize grow height 3 px or 3 ppt
        bindsym k resize shrink height 3 px or 3 ppt
        bindsym l resize grow width 3 px or 3 ppt
	bindsym Left resize shrink width 3 px or 3 ppt
        bindsym Down resize grow height 3 px or 3 ppt
        bindsym Up resize shrink height 3 px or 3 ppt
        bindsym Right resize grow width 3 px or 3 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}
bindsym $mod+r mode "$mode_resize"

### GAPS ###

# smart_gaps on
# smart_borders no_gaps
# gaps top 10
gaps inner 7
gaps outer 5
default_border pixel 0
set $mode_gaps GAPS: Outer / Inner
set $mode_inner_gaps Inner: [Shift] +, -, 0
set $mode_outer_gaps Outer: [Shift] +, -, 0
bindsym $mod+g mode "$mode_gaps"
mode "$mode_gaps" {
        bindsym o mode "$mode_outer_gaps"
        bindsym i mode "$mode_inner_gaps"

        bindsym Escape mode "default"
        bindsym Return mode "default"
}
mode "$mode_inner_gaps" {
        bindsym Shift+plus  gaps inner current plus 2
        bindsym Shift+minus gaps inner current minus 2
        bindsym Shift+0     gaps inner current set 0

        bindsym plus  gaps inner all plus 2
        bindsym minus gaps inner all minus 2
        bindsym 0     gaps inner all set 0

        bindsym Escape mode "default"
        bindsym Return mode "default"
}
mode "$mode_outer_gaps" {
        bindsym Shift+plus  gaps outer current plus 2
        bindsym Shift+minus gaps outer current minus 2
        bindsym Shift+0     gaps outer current set 0

        bindsym plus  gaps outer all plus 2
        bindsym minus gaps outer all minus 2
        bindsym 0     gaps outer all set 0

        bindsym Escape mode "default"
        bindsym Return mode "default"
}


### PROGRAMS ###

set $mode_launcher Shortcuts: B, C, D, E, F, G, M, N, O, P, S, T, [shift|ctrl]V, W, Z
bindsym $mod+o mode "$mode_launcher"
mode "$mode_launcher" {
    bindsym b exec bitwarden-desktop
    bindsym c exec code --enable-proposed-api ms-python.python
    bindsym d exec discord
    bindsym e exec nemo
    bindsym f exec catfish
    bindsym g exec github-desktop
#     bindsym m exec alacritty -e ncmpcpp
    bindsym m exec thunderbird
    bindsym n exec appimage supernotes
    bindsym o exec obs
    bindsym p exec zathura
    bindsym s exec spotify
    bindsym t exec telegram-desktop
    bindsym v exec alacritty -e nvim
    bindsym Shift+v exec virtualbox
    bindsym ctrl+v exec virt-manager
    bindsym w exec firefox
    bindsym z exec zoom

    bindsym Escape mode "default"
    bindsym Return mode "default"
}
