#!/usr/bin/env bash

set $mod Mod4
set $alt Mod1
# set $refresh_i3status killall -SIGUSR1 i3status
set $i3res i3-msg restart
floating_modifier $mod

### INITIAL STARTUPS ###

# Picom
exec_always --no-startup-id picom &

# Dunst
exec_always --no-startup-id dunst &

# Enabling Touchpad tapping
exec --no-startup-id xinput set-prop $(xinput list | rg "Touchpad\s+id=(\d+)" -or '$1') "libinput Tapping Enabled" 1

# Restore prev screen brightness
exec_always --no-startup-id light -I

# Try to start with both monitors
exec_always --no-startup-id ~/.bin/monitor both &

# Set random background image
exec_always --no-startup-id nitrogen --no-recurse --set-scaled --random ~/Pictures/wallpapers/
# exec --no-startup-id feh --no-fehbg --bg-scale --no-xinerama $(ls ~/Pictures/wallpapers/*.jpg | sort -R | head -n1)
# exec --no-startup-id feh --no-fehbg --bg-scale ~/Pictures/wallpapers/$(ls ~/Pictures/wallpapers | shuf | head -1)

# Screen autolock and system suspend (14+1 min)
exec --no-startup-id ~/.bin/screenlock autosuspend &

# Polybar
exec_always --no-startup-id ~/.config/polybar/launch.sh &

# Battery level monitor
exec_always --no-startup-id ~/.bin/battery 20 99 60 &

# mpd
exec_always --no-startup-id mpd &

### FONT ###

font Hack 10

### SOUND ###

# volume
bindsym XF86AudioLowerVolume exec --no-startup-id pamixer -d 5 # && ~/.bin/volume &
bindsym XF86AudioRaiseVolume exec --no-startup-id pamixer -i 5 # && ~/.bin/volume &
# atomic volume
bindsym $mod+XF86AudioLowerVolume exec --no-startup-id pamixer -d 1 # && ~/.bin/volume &
bindsym $mod+XF86AudioRaiseVolume exec --no-startup-id pamixer -i 1 # && ~/.bin/volume &
# toggle audio
bindsym XF86AudioMute exec --no-startup-id pamixer --toggle-mute # && ~/.bin/volume &
# toggle mic
bindsym XF86AudioMicMute exec --no-startup-id pamixer --default-source --toggle-mute # && ~/.bin/microphone &
# audio player
# bindsym XF86AudioPlay exec --no-startup-id playerctl play
# bindsym XF86AudioPause exec --no-startup-id playerctl pause
# bindsym XF86AudioNext exec --no-startup-id playerctl next
# bindsym XF86AudioPrev exec --no-startup-id playerctl previous

### TOUCHPAD ###

bindsym XF86TouchpadToggle exec --no-startup-id ~/.bin/touchpad &

### BRIGHTNESS ###
bindsym XF86MonBrightnessDown exec --no-startup-id light -U 2 && light -O # && ~/.bin/brightness & # -O = save
bindsym XF86MonBrightnessUp exec --no-startup-id light -A 2 && light -O # && ~/.bin/brightness & # -O = save

### KEYBINDINGS ###

# start a terminal
bindsym $mod+a exec --no-startup-id alacritty

# Turn off and Lock screen (random wallpaper)
bindsym ctrl+$alt+l exec --no-startup-id ~/.bin/screenlock lock &

# Adjust monitors
bindsym ctrl+$alt+b exec --no-startup-id ~/.bin/monitor main && $i3res
bindsym ctrl+$alt+n exec --no-startup-id ~/.bin/monitor ext && $i3res
bindsym ctrl+$alt+m exec --no-startup-id ~/.bin/monitor both && $i3res

# move workspaces between monitors
bindsym $mod+n move workspace to output left
bindsym $mod+m move workspace to output right

# kill focused window
bindsym $mod+Shift+q kill
bindsym $alt+F4 kill

# start Rofi launcher
bindsym Menu exec --no-startup-id rofi -show drun
bindsym $mod+Escape exec --no-startup-id ~/.bin/rofi-powermenu

# Flameshot screenshots
# manual region
bindsym ctrl+Print flameshot gui -c
# active screen
bindsym Print flameshot screen -c

# change focus
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+ctrl+h split h

# split in vertical orientation
bindsym $mod+ctrl+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen toggle

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
# bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+Shift+a focus parent

# focus the child container
#bindsym $mod+d focus child

# Define names for default workspaces for which we configure key bindings later on.
# We use variables to avoid repeating the names in multiple places.
set $ws1 "1"
set $ws2 "2"
set $ws3 "3"
set $ws4 "4"
set $ws5 "5"
set $ws6 "6"
set $ws7 "7"
set $ws8 "8"
set $ws9 "9"
set $ws10 "10"

# switch to workspace
bindsym $mod+1 workspace number $ws1
bindsym $mod+2 workspace number $ws2
bindsym $mod+3 workspace number $ws3
bindsym $mod+4 workspace number $ws4
bindsym $mod+5 workspace number $ws5
bindsym $mod+6 workspace number $ws6
bindsym $mod+7 workspace number $ws7
bindsym $mod+8 workspace number $ws8
bindsym $mod+9 workspace number $ws9
bindsym $mod+0 workspace number $ws10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace number $ws1
bindsym $mod+Shift+2 move container to workspace number $ws2
bindsym $mod+Shift+3 move container to workspace number $ws3
bindsym $mod+Shift+4 move container to workspace number $ws4
bindsym $mod+Shift+5 move container to workspace number $ws5
bindsym $mod+Shift+6 move container to workspace number $ws6
bindsym $mod+Shift+7 move container to workspace number $ws7
bindsym $mod+Shift+8 move container to workspace number $ws8
bindsym $mod+Shift+9 move container to workspace number $ws9
bindsym $mod+Shift+0 move container to workspace number $ws10

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"
# restore and save layout with i3-resurrect
bindsym $mod+t exec --no-startup-id i3-resurrect restore
bindsym $mod+y exec --no-startup-id i3-resurrect save


# resize window (you can also use the mouse for that)
set $mode_resize Resizing active window
mode "$mode_resize" {
        bindsym h resize shrink width 3 px or 3 ppt
        bindsym j resize grow height 3 px or 3 ppt
        bindsym k resize shrink height 3 px or 3 ppt
        bindsym l resize grow width 3 px or 3 ppt
	bindsym Left resize shrink width 3 px or 3 ppt
        bindsym Down resize grow height 3 px or 3 ppt
        bindsym Up resize shrink height 3 px or 3 ppt
        bindsym Right resize grow width 3 px or 3 ppt

        bindsym Return mode "default"
        bindsym Escape mode "default"
        bindsym $mod+r mode "default"
}

bindsym $mod+r mode "$mode_resize"

### GAPS ###

# gaps top 10
gaps outer 5
gaps inner 10
# smart_gaps on
# smart_borders on

set $mode_gaps Gaps: [i]nner, [o]uter
set $mode_inner_gaps Inner gaps: +|-|0 (local; global with Shift)
set $mode_outer_gaps Outer gaps: +|-|0 (local; global with Shift)
bindsym $mod+g mode "$mode_gaps"

mode "$mode_gaps" {
        bindsym o mode "$mode_outer_gaps"
        bindsym i mode "$mode_inner_gaps"

        bindsym Escape mode "default"
        bindsym Return mode "default"
}
mode "$mode_inner_gaps" {
        bindsym plus  gaps inner current plus 2
        bindsym minus gaps inner current minus 2
        bindsym 0     gaps inner current set 0

        bindsym Shift+plus  gaps inner all plus 2
        bindsym Shift+minus gaps inner all minus 2
        bindsym Shift+0     gaps inner all set 0

        bindsym Escape mode "default"
        bindsym Return mode "default"
}
mode "$mode_outer_gaps" {
        bindsym plus  gaps outer current plus 2
        bindsym minus gaps outer current minus 2
        bindsym 0     gaps outer current set 0

        bindsym Shift+plus  gaps outer all plus 2
        bindsym Shift+minus gaps outer all minus 2
        bindsym Shift+0     gaps outer all set 0

        bindsym Escape mode "default"
        bindsym Return mode "default"
}

### BORDERS ###

default_border pixel 2
# for_window [class="^.*"] border pixel 2

### APPS SHORTCUTS ###

set $mode_launcher Application shortcuts: W, T, C, B, V, E, D, Z, S, F, Esc|Enter
bindsym $mod+o mode "$mode_launcher"
mode "$mode_launcher" {
    bindsym b exec bitwarden
    bindsym c exec code-oss
    bindsym d exec discord
    bindsym e exec nemo
    bindsym f exec catfish
    bindsym s exec spotify
    bindsym t exec telegram-desktop
    bindsym v exec realvnc-vnc-viewer
    bindsym w exec firefox
    bindsym z exec zoom

    bindsym Escape mode "default"
    bindsym Return mode "default"
}
