#!/usr/bin/env bash

usage() { echo -e "Usage:\t$(basename "$0") <namestring>" && exit 1; }
[ $# -eq 0 ] && usage

name=$1
[ "$name" ] || {
  echo "Provide a pattern string"
  exit 1
}

list=$(find "$HOME/apps" -regextype egrep -iregex ".*$name.*\.(AppImage)$")
count=$(echo "$list" | wc -l)

if ((count > 1)); then
  echo -e "Found multiple .AppImage files for \"$name\":\n\n$list\n\nTry to be more specific." && exit 1
elif ((count == 0)); then
  echo "No .AppImage found for \"$name\"" && exit 1
# == 1
else
  [ -x "$list" ] || {
    echo "Run \"chmod +x $list\" first"
    exit 1
  }
  "$list"
fi
