#!/usr/bin/env bash

usage() { echo -e "Usage:\t$(basename "$0") -l <low> -h <high> -i <interval>" && exit 1; }
[ $# -eq 0 ] && usage

while getopts ":l:h:i:" opt; do
  case $opt in
  l) low=$OPTARG ;;
  h) high=$OPTARG ;;
  i) interval=$OPTARG ;;
  *) usage ;;
  esac
done

# kill other running instances of the current script if present
for pid in $(pgrep -f "$0"); do
  [ "$pid" -ne $$ ] && kill "$pid" &>/dev/null
done

bat_path=$(upower -e | grep BAT)
icons="$XDG_DATA_HOME/icons"

while true; do
  cur_lvl=$(upower -i "$bat_path" | grep -E "percentage" | sed 's/[^0-9]//g')
  discharging=$(upower -i "$bat_path" | grep -E "state" | grep -c discharging)

  # <=low and discharging
  if [ "$cur_lvl" -le "$low" ] && [ "$discharging" -eq 1 ]; then
    message="Low battery: $cur_lvl%"
  # >=high and charging
  # elif [ "$cur_lvl" -ge "$high" ] && [ "$discharging" -eq 0 ]; then
  #   message="Battery charged: $cur_lvl%"
  fi

  [ -n "$message" ] && {
    dunstify \
      -a "Battery" \
      -r 1 \
      -i "$icons/battery.svg" \
      -u CRITICAL \
      "$message"
    unset message
  }

  sleep "$interval"
done
