#!/usr/bin/env bash

ssh_app=$1
ssh_host=$2

if [ "$ssh_app" ] && [ "$ssh_host" ]; then
	locdir="$HOME/coding/$ssh_app/honeybot"
	remdir="$HOME/python/$ssh_app/honeybot"
	rsync -ahPuvz --exclude-from="$locdir/rsync.exclude" "$locdir/" "$ssh_host:$remdir/" &>"$locdir/rsync.log" &
else
	echo "Missing arguments"
	exit 1
fi
