#!/usr/bin/env bash

# packages
paru -Scq --noconfirm
paccache -ruq
sudo pacman -Rnus $(sudo pacman -Qdtq --noconfirm) 2>/dev/null

# home files
rm ~/.{lesshst,wget-hsts} 2>/dev/null

# ~/.cache
shopt -s extglob
pushd ~/.cache/ &>/dev/null || exit 1
rm -rf !(betterlockscreen|ImageMagick|fontconfig) 2>/dev/null
popd &>/dev/null || exit 1
shopt -u extglob
