#!/usr/bin/env bash

usage() { echo -e "Usage:\t$(basename "$0") <file1.c> [... <fileN.c>]" && exit 1; }
[ $# -eq 0 ] && usage

files=("$@")
outs=()

for file in "${files[@]}"; do
  if [[ $(file "$file") =~ "C source" ]]; then
    out=${file%.*}
    gcc "$file" -o "$out" && outs+=("$out")
  else
    echo -e "Err: skipped \"$file\", not a C script\n"
  fi
done

for out in "${outs[@]}"; do
  echo -e "Running \"$out\":"
  ./"$out"
  echo
done
