#!/usr/bin/env bash

usage() { echo -e "Usage:\t$(basename "$0") <script.c> [args]" && exit 1; }
[ $# -eq 0 ] && usage

script=$1
if [[ $(file "$script") =~ "C source" ]]; then
  out=${script%.*}
  gcc "$script" -o "$out" || exit 1

  printf "Running $LGREEN%s$NC " "$out"
  args="${*:2:$#}"
  [ -n "$args" ] && {
    printf "with arguments: "
    printf "$LGREEN%s$NC" "$args"
  }
  printf "\n\n"

  ./"$out" ${args[@]} # explode string in array of arguments
  rm "$out"
else
  echo -e "Err: not a C script\n" && exit 1
fi
