#!/usr/bin/env bash

cur_state=$(pamixer --default-source --get-mute)

icons="$XDG_DATA_HOME/icons"
# shellcheck disable=2015
[ "$cur_state" = "true" ] && {
  icon="mic-off"
  state="ON"
} || {
  icon="mic"
  state="OFF"
}

dunstify \
  -a "Microphone" \
  -r 3 \
  -i "$icons/$icon.svg" \
  "Mic $state"
