#!/usr/bin/env bash

usage() { echo -e "Usage:\t$(basename "$0") <int|ext|both>" && exit 1; }
[ $# -eq 0 ] && usage

# get the list of all the possible monitors: eDP1 DP1 [HDMI1] [VIRTUAL1]
## N.B: remember to change the "ext" accordingly
read -d'\n' -r int ext _ _ < <(xrandr --query | tail -n+2 | rg "^\w+" -o)
# rg "(\d+)/\d+x(\d+).+ (\w+)$" -or '$1 $2 $3')

mon=$1
defined_list=$(xrandr --listmonitors)
full_list=$(xrandr --query)

# get then anyway (preferred res, first line - highest freq)
intres=$(sed -n "/^$int/{n;p;q}" <<< "$full_list" | rg "\d+x\d+" -o)
extres=$(cat /tmp/"${ext}"_res)

# fallback to int mon if no ext
# rg " $ext$" <<< "$defined_list" >/dev/null || mon="$int"

wps=~/Pictures/wallpapers
nitroconf="$XDG_CONFIG_HOME"/nitrogen/bg-saved.cfg

set_bg() {
  screen=$1
  res=$2
  rg "xin_${screen}" "$nitroconf" >/dev/null || nitrogen --head="$screen" --save --set-scaled "$wps"/wp_"$res" &
}

set_Lbg() {
  res=$1
  [ -d "$XDG_CACHE_HOME"/betterlockscreen ] || betterlockscreen -u "$wps"/Lwp_"$res" -q &
}

case "$mon" in
int)
  xrandr \
    --output "$int" --primary --mode $intres \
    --output "$ext" --off
  set_bg 0 "$intres"
  set_Lbg "$intres"
  list="$int"
  ;;
ext)
  xrandr \
    --output "$int" --off \
    --output "$ext" --primary --mode $extres
  set_bg 0 "$extres"
  set_Lbg "$extres"
  list="$ext"
  ;;
both)
  xrandr \
    --output "$int" --pos 0x282 --mode $intres \
    --output "$ext" --pos 1366x0 --primary --mode $extres
  set_bg 1 "$intres"
  set_bg 0 "$extres"
  # choose biggest res for lockscreen
  set_Lbg "$extres"
  list="$int, $ext"
  ;;
h | *) usage ;;
esac

# restart i3
i3-msg restart >/dev/null

icons="$XDG_DATA_HOME/icons"
dunstify \
  -a "Monitor" \
  -r 5 \
  -i "$icons/monitor.svg" \
  "Active monitor(s): $list"

exit 0
