#!/usr/bin/env bash

mon=$1
[[ "$mon" =~ ^main|ext|both$ ]] || {
   echo -e "Usage:\t$(basename "$0") <main|ext|both>"
   exit 1
}

# Check for another connected monitor
connected=$(xrandr --query | grep '\bconnected\b')
count=$(echo "$connected" | wc -l)
if [ "$count" -lt 2 ]; then
   echo "Can't find a second monitor"
   exit 1
fi

case "$mon" in
main)
   xrandr --output DP1 --off \
      --output eDP1 --primary --mode 1366x768 --pos 0x0 --rotate normal \
      --output HDMI-1 --off
   ex
   ;;
ext)
   xrandr --output eDP1 --off \
      --output DP1 --primary --mode 1680x1050 --pos 0x0 --rotate normal \
      --output HDMI-1 --off
   ;;
both)
   xrandr --output DP1 --primary --mode 1680x1050 --pos 1366x0 --rotate normal \
      --output eDP1 --mode 1366x768 --pos 0x283 --rotate normal \
      --output HDMI-1 --off
   ;;
esac

exit 0
