#!/usr/bin/env bash

usage() { echo -e "Usage:\t$(basename "$0") <dir1> [... <dirN>]" && exit 1; }
[ $# -eq 0 ] && usage

dirs=("$@")

for dir in "${dirs[@]}"; do
	# exit on fail
	[ -d "$dir" ] || usage

	pushd "$dir" || continue
	for vid in ./*.mp4; do
		ffmpeg -i "$vid" \
			-c:v libx264 -crf 40 -filter:v fps=fps=10 -c:a libopus -application voip -ab 16k -ac 1 -cutoff 12000 \
			"$(echo "$vid" | sed 's/mp4/mkv/')"
	done
	popd || continue
done
