#!/usr/bin/env bash

path=~/uni/cybersec
[ ! -d "$path" ] && { "Path \"$path\" not found, aborting."; exit 1; }

rclone sync "$path" cybersec: --exclude "video/**" --update --progress && \
  echo -e "\nCleaning remote empty dirs..." && \
  rclone rmdirs cybersec: --leave-root
