#!/usr/bin/env bash

path=~/uni/cybersec
rclone sync $path cybersec: --exclude "video/**" --update --progress && \
{ echo -e "\nCleaning remote empty dirs..." ; rclone rmdirs cybersec: --leave-root ; }
