#!/usr/bin/env bash

usage() { echo -e "Usage:\t$(basename "$0") <1a1s|1a2s|2a1s|2a2s>" && exit 1; }
[ $# -eq 0 ] && usage

dir=$1
if [[ "$dir" =~ ^[12]a[12]s$ ]]; then
  path=~/uni/cybersec/"$dir"
  rclone copy "$path" mega_am:cybersec/"$dir" --include "/**/video/**" --update --progress && \
  echo -e "\nCleaning remote empty dirs..." && \
  rclone rmdirs mega_am: --leave-root
else
  usage
fi
