#!/usr/bin/env bash

sleep 3
file_id=$RANDOM
ffmpeg -f x11grab -video_size 1366x768 -framerate 10 -i "$DISPLAY" -f pulse -i alsa_output.pci-0000_00_1f.3.analog-stereo.monitor -preset ultrafast -c:v libx264 -crf 40 -pix_fmt yuv420p \
  "/home/andrea/recscreen${file_id}.mp4"
