#!/usr/bin/env bash

wd="$HOME/audio/rickroll"
audio="$wd/audio.wav"
video="$wd/video.bz2"

clear

# stream audio
aplay -Dplug:default -q -f S16_LE -r 8000 "$audio" &

# stream video
python3 <(
  cat <<EOF
import sys
import time
fps = 25; time_per_frame = 1.0 / fps
buf = ''; frame = 0; next_frame = 0
begin = time.time()
try:
  for i, line in enumerate(sys.stdin):
    if i % 32 == 0:
      frame += 1
      sys.stdout.write(buf); buf = ''
      elapsed = time.time() - begin
      repose = (frame * time_per_frame) - elapsed
      if repose > 0.0:
        time.sleep(repose)
      next_frame = elapsed / time_per_frame
    if frame >= next_frame:
      buf += line
except KeyboardInterrupt:
  pass
EOF
) < <(bunzip2 -q "$video" 2>/dev/null)

clear
