#!/usr/bin/env bash

usage() { echo -e "Usage:\t$(basename "$0") <lock|autolock>" && exit 1; }
[ $# -eq 0 ] && usage

# look for cached file
[ -d "$HOME/.cache/betterlockscreen/" ] || betterlockscreen -u ~/Pictures/wallpapers/lockscreen.png --fx blur -q

case "$1" in
lock)
	light -O
	light -S25 && betterlockscreen -l blur --off 300
	light -I
	;;

autosuspend)
	killall -9 xidlehook
	xidlehook \
		--not-when-fullscreen \
		--not-when-audio \
		--timer 540 'light -O && light -S5' \
		--timer 60 'light -S25 && betterlockscreen -l blur' \
		--timer 300 'light -I && systemctl suspend'
	;;
h | *) usage;;
esac

# font="dedede"
# green="9ece6a"
# red="db4b4b"
# # --image "$(find ~/Pictures/wallpapers/ -name "*.jpg" | sort -R | tail -1)" \
# i3lock --nofork --force-clock --ignore-empty-password -F \
# 	--image /usr/share/sddm/themes/sddm-flower-theme/Backgrounds/background.png \
# 	--refresh-rate=1 --line-uses-inside --pointer=default --pass-media-keys --pass-volume-keys --pass-screen-keys \
# 	--inside-color="$green" --ring-color="$green" --insidever-color="$green" --ringver-color="$green" --insidewrong-color="$red" --ringwrong-color="$red" \
# 	--keyhl-color="$green" --separator-color="$green" --bshl-color="$green" --color=000000 \
# 	--time-str="%H:%M:%S" --time-size=140 --time-pos="960:300" --time-font="Roboto mono:style=Bold" --time-color="$font" \
# 	--date-str="%A %d %B" --date-size=45 --date-pos="960:380" --date-font="Roboto mono" --date-color="$font" \
# 	--verif-text="Verifying" --greeter-text="" --wrong-text="Wrong Password!" --noinput-text="No input" \
# 	--verif-font="Roboto mono" --greeter-font="Roboto mono" --wrong-font="Roboto mono" \
# 	--verif-size=35 --greeter-size=35 --wrong-size=35 \
# 	--verif-pos="960:540" --greeter-pos="960:600" --wrong-pos="960:540" \
# 	--verif-color="$green" --greeter-color="$font" --wrong-color="$red" \
# 	--bar-indicator --bar-direction=0 --bar-step=10 --bar-max-height=10 --bar-base-width=10 --bar-total-width=1920 --bar-color=00000000 --bar-pos="0:1070"

# turn off screen \

# BLANK='#00000000' # blank
# CLEAR='#ffffff22' # clear ish

# YTISH='#ffffffaa' # white-ish
# WHITE='#ffffffff' # white
# RED='#d92121ff'
# DARK='#142b47ff'
# RUST='#6e0b0bff'

# i3lock-fancy-rapid \
# 	5 pixel \
# 	--nofork \
# 	\
# 	--insidevercolor=$CLEAR \
# 	--ringvercolor=$WHITE \
# 	\
# 	--insidewrongcolor=$CLEAR \
# 	--ringwrongcolor=$RED \
# 	\
# 	--insidecolor=$BLANK \
# 	--ringcolor=$YTISH \
# 	--linecolor=$BLANK \
# 	--separatorcolor=$DARK \
# 	\
# 	--verifcolor=$WHITE \
# 	--wrongcolor=$WHITE \
# 	--timecolor=$WHITE \
# 	--datecolor=$WHITE \
# 	--keyhlcolor=$DARK \
# 	--bshlcolor=$RUST \
# 	\
# 	--indicator \
# 	--radius=25 \
# 	--indpos="x+85:y+1040" \
# 	--force-clock \
# 	--timestr="%R" \
# 	--timepos="x+1900:iy" \
# 	--time-font="Rubik" \
# 	--date-font="Rubik" \
# 	\
# 	--veriftext="" \
# 	--wrongtext="" \
# 	--noinputtext="" \
# 	--timesize=48
# # --modsize=10
# # --timefont=comic-sans
# # --datefont=monofur
# # etc
