#!/usr/bin/env bash

id=$(xinput | grep -i "TouchPad" | cut -f 2 | cut -d= -f 2)
status=$(xinput --list-props "$id" | grep "Device Enabled" | cut -f 3)

if [ "$status" -eq 1 ]; then
    xinput --disable "$id"
else
    xinput --enable "$id"
fi
