#!/usr/bin/env bash

# cur_vol=$(awk -F"[][]" '/Left:/ { print $2 }' <(amixer sget Master) | sed 's/%//g')
cur_vol=$(pamixer --get-volume)
low_vol=33
high_vol=66

if [[ "$cur_vol" =~ ^0|muted$ ]]; then
  icon="x"
elif [ "$cur_vol" -lt $low_vol ]; then
  icon=1
elif [ "$cur_vol" -ge $low_vol ] && [ "$cur_vol" -le $high_vol ]; then
  icon=2
elif [ "$cur_vol" -gt $high_vol ]; then
  icon=3
fi

dunstify \
  -a "Speakers" \
  -r 6 \
  -i ~/.icons/volume-$icon.svg \
  "Speakers volume: $cur_vol%"

# how=$1
# value=$2
# script=$(basename "$0")

# if [[ "$how" == "down" ]]; then
#   # pactl set-sink-volume @DEFAULT_SINK@ -"$value"%
#   amixer sset Master $value%-
#   new=$(awk '/%/ {gsub(/[\[\]]/,""); print $4}' <(amixer sget Master))
#   notify-send --urgency=low --expire-time=50 --app-name="$script" "Down to $new"
# elif [[ "$how" == "up" ]]; then
#   # pactl set-sink-volume @DEFAULT_SINK@ +"$value"%
#   amixer sset Master $value%+
#   new=$(awk '/%/ {gsub(/[\[\]]/,""); print $4}' <(amixer sget Master))
#   notify-send --urgency=low --expire-time=50 --app-name="$script" "Up to $new"
# fi
