#!/bin/bash

pacman_packages=()
# documents and coding
pacman_packages+=("thunar" "qpdfview" "code" "mysql-workbench" "pgadmin4" "postgresql")
# img, sound and video
pacman_packages+=("flameshot" "obs-studio" "vlc")
# Internet, network & security
pacman_packages+=("telegram-desktop-bin firefox rclone iptables-nft bitwarden zoom realvnc-vnc-viewer discord_arch_electron")
# virtualization
pacman_packages+=("virt-manager" "qemu" "qemu-arch-extra" "ovmf" "vde2" "edk2-ovmf" "ebtables" "dnsmasq" "bridge-utils" "openbsd-netcat")
# system
pacman_packages+=("exa" "catfish" "htop" "fastfetch" "tlpui" "stacer" "gparted" "grub-customizer")

aur_packages=()
# img, sound and video
aur_packages+=("tenacity-git")
# coding
aur_packages+=("github-desktop-bin")
# social
aur_packages+=("spotify")
# devices
aur_packages+=("realvnc-vnc-viewer")
# system
aur_packages+=("ly" "zramd" "timeshift-bin" "timeshift-autosnap")
